[tool.poetry]
name = "ai-utils"
version = "0.1.0"
description = "AI utilities for the playground monorepo"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
